/* eslint-disable react/no-unknown-property */
/* eslint-disable no-unused-vars */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/models/uploads_files_3248566_miniNY.gltf --transform
Files: public/models/uploads_files_3248566_miniNY.gltf [7.2MB] > uploads_files_3248566_miniNY-transformed.glb [126.42KB] (98%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'

export function City(props) {
  const { nodes, materials } = useGLTF('/models/uploads_files_3248566_miniNY-transformed.glb')

  materials.Default = new THREE.MeshPhongMaterial({
    color: 0xffffff,      // Set the base color to white
  });
  return (
    <>
      <group position={[
        0, 0, -2
      ]}>
        <group {...props} dispose={null}
          position={[3, -2, -8]}
          scale={[0.01, 0.01, 0.01]}
          rotation={[Math.PI / 2, Math.PI / 2, 0]}
        >

          <mesh geometry={nodes.Plane.geometry} material={
            materials.Default
          }
            castShadow
            receiveShadow={true}
          />


        </group>
        <mesh position={[0, 0, -8]}>
          <planeGeometry args={[30, 30]} />
          <meshPhongMaterial color={0x00267E}
            shininess={500}
          />
        </mesh>
      </group>
    </>
  )
}

useGLTF.preload('/uploads_files_3248566_miniNY-transformed.glb')
