/* eslint-disable react/no-unknown-property */
/* eslint-disable no-unused-vars */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/models/coffee_shop.glb --transform
Files: public/models/coffee_shop.glb [27.6MB] > coffee_shop-transformed.glb [646.06KB] (98%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function CoffeeShop(props) {
  const { nodes, materials } = useGLTF('./coffee_shop-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.box.geometry} material={materials.PaletteMaterial001} position={[1.935, 0.633, 2.58]} rotation={[-1.799, -0.13, 2.08]} scale={[0.02, 0.54, 0.68]} />
      <mesh geometry={nodes.box_1.geometry} material={materials.PaletteMaterial002} position={[-2.945, 2.445, 1.065]} scale={[0.05, 3.94, 2.13]} />
      <instancedMesh args={[nodes.mesh_0.geometry, materials.PaletteMaterial001, 9]} instanceMatrix={nodes.mesh_0.instanceMatrix} />
      <instancedMesh args={[nodes.mesh_1.geometry, materials.PaletteMaterial001, 32]} instanceMatrix={nodes.mesh_1.instanceMatrix} />
      <instancedMesh args={[nodes.mesh_2.geometry, materials.PaletteMaterial001, 40]} instanceMatrix={nodes.mesh_2.instanceMatrix} />
      <instancedMesh args={[nodes.mesh_3.geometry, materials.PaletteMaterial001, 24]} instanceMatrix={nodes.mesh_3.instanceMatrix} />
      <instancedMesh args={[nodes.mesh_4.geometry, materials.PaletteMaterial001, 23]} instanceMatrix={nodes.mesh_4.instanceMatrix} />
      <instancedMesh args={[nodes.mesh_5.geometry, materials.PaletteMaterial001, 12]} instanceMatrix={nodes.mesh_5.instanceMatrix} />
      <instancedMesh args={[nodes.mesh_6.geometry, materials.PaletteMaterial001, 6]} instanceMatrix={nodes.mesh_6.instanceMatrix} />
      <instancedMesh args={[nodes.mesh_7.geometry, materials.PaletteMaterial001, 40]} instanceMatrix={nodes.mesh_7.instanceMatrix} />
      <instancedMesh args={[nodes.mesh_8.geometry, materials.PaletteMaterial001, 31]} instanceMatrix={nodes.mesh_8.instanceMatrix} />
      <instancedMesh args={[nodes.mesh_9.geometry, materials.PaletteMaterial001, 6]} instanceMatrix={nodes.mesh_9.instanceMatrix} />
      <instancedMesh args={[nodes.mesh_10.geometry, materials.PaletteMaterial001, 111]} instanceMatrix={nodes.mesh_10.instanceMatrix} />
      <instancedMesh args={[nodes.mesh_11.geometry, materials.PaletteMaterial001, 10]} instanceMatrix={nodes.mesh_11.instanceMatrix} />
      <instancedMesh args={[nodes.mesh_12.geometry, materials.PaletteMaterial001, 10]} instanceMatrix={nodes.mesh_12.instanceMatrix} />
      <instancedMesh args={[nodes.mesh_13.geometry, materials.PaletteMaterial001, 13]} instanceMatrix={nodes.mesh_13.instanceMatrix} />
      <instancedMesh args={[nodes.mesh_14.geometry, materials.PaletteMaterial001, 13]} instanceMatrix={nodes.mesh_14.instanceMatrix} />
      <instancedMesh args={[nodes.mesh_15.geometry, materials.PaletteMaterial001, 12]} instanceMatrix={nodes.mesh_15.instanceMatrix} />
      <instancedMesh args={[nodes.mesh_16.geometry, materials.PaletteMaterial001, 12]} instanceMatrix={nodes.mesh_16.instanceMatrix} />
      <instancedMesh args={[nodes.mesh_17.geometry, materials.PaletteMaterial001, 6]} instanceMatrix={nodes.mesh_17.instanceMatrix} />
      <instancedMesh args={[nodes.mesh_19.geometry, materials.PaletteMaterial001, 8]} instanceMatrix={nodes.mesh_19.instanceMatrix} />
      <instancedMesh args={[nodes.mesh_20.geometry, materials.PaletteMaterial001, 7]} instanceMatrix={nodes.mesh_20.instanceMatrix} />
      <instancedMesh args={[nodes.mesh_21.geometry, materials.PaletteMaterial001, 5]} instanceMatrix={nodes.mesh_21.instanceMatrix} />
      <instancedMesh args={[nodes.mesh_22.geometry, materials.PaletteMaterial002, 5]} instanceMatrix={nodes.mesh_22.instanceMatrix} />
      <instancedMesh args={[nodes.mesh_23.geometry, materials.PaletteMaterial002, 5]} instanceMatrix={nodes.mesh_23.instanceMatrix} />
      <instancedMesh args={[nodes.mesh_24.geometry, materials.PaletteMaterial002, 6]} instanceMatrix={nodes.mesh_24.instanceMatrix} />
      <instancedMesh args={[nodes.mesh_25.geometry, materials.PaletteMaterial002, 7]} instanceMatrix={nodes.mesh_25.instanceMatrix} />
      <instancedMesh args={[nodes.mesh_26.geometry, materials.PaletteMaterial001, 84]} instanceMatrix={nodes.mesh_26.instanceMatrix} />
      <instancedMesh args={[nodes.mesh_27.geometry, materials.PaletteMaterial001, 9]} instanceMatrix={nodes.mesh_27.instanceMatrix} />
      <instancedMesh args={[nodes.mesh_28.geometry, materials.PaletteMaterial001, 9]} instanceMatrix={nodes.mesh_28.instanceMatrix} />
      <instancedMesh args={[nodes.mesh_29.geometry, materials.PaletteMaterial001, 5]} instanceMatrix={nodes.mesh_29.instanceMatrix} />
      <instancedMesh args={[nodes.mesh_30.geometry, materials.PaletteMaterial001, 5]} instanceMatrix={nodes.mesh_30.instanceMatrix} />
      <instancedMesh args={[nodes.mesh_31.geometry, materials.PaletteMaterial001, 21]} instanceMatrix={nodes.mesh_31.instanceMatrix} />
      <instancedMesh args={[nodes.mesh_32.geometry, materials.PaletteMaterial001, 6]} instanceMatrix={nodes.mesh_32.instanceMatrix} />
      <instancedMesh args={[nodes.mesh_33.geometry, materials.PaletteMaterial001, 8]} instanceMatrix={nodes.mesh_33.instanceMatrix} />
      <instancedMesh args={[nodes.mesh_34.geometry, materials.PaletteMaterial001, 9]} instanceMatrix={nodes.mesh_34.instanceMatrix} />
      <instancedMesh args={[nodes.mesh_35.geometry, materials.PaletteMaterial001, 11]} instanceMatrix={nodes.mesh_35.instanceMatrix} />
      <instancedMesh args={[nodes.mesh_36.geometry, materials.PaletteMaterial001, 5]} instanceMatrix={nodes.mesh_36.instanceMatrix} />
      <instancedMesh args={[nodes.mesh_37.geometry, materials.PaletteMaterial002, 5]} instanceMatrix={nodes.mesh_37.instanceMatrix} />
      <instancedMesh args={[nodes.mesh_38.geometry, materials.PaletteMaterial001, 6]} instanceMatrix={nodes.mesh_38.instanceMatrix} />
      <instancedMesh args={[nodes.mesh_39.geometry, materials.PaletteMaterial001, 202]} instanceMatrix={nodes.mesh_39.instanceMatrix} />
      <instancedMesh args={[nodes.mesh_40.geometry, materials.PaletteMaterial001, 128]} instanceMatrix={nodes.mesh_40.instanceMatrix} />
      <instancedMesh args={[nodes.mesh_41.geometry, materials.PaletteMaterial001, 198]} instanceMatrix={nodes.mesh_41.instanceMatrix} />
      <instancedMesh args={[nodes.mesh_42.geometry, materials.PaletteMaterial001, 23]} instanceMatrix={nodes.mesh_42.instanceMatrix} />
      <instancedMesh args={[nodes.mesh_43.geometry, materials.PaletteMaterial001, 124]} instanceMatrix={nodes.mesh_43.instanceMatrix} />
      <instancedMesh args={[nodes.mesh_44.geometry, materials.PaletteMaterial001, 13]} instanceMatrix={nodes.mesh_44.instanceMatrix} />
      <instancedMesh args={[nodes.mesh_45.geometry, materials.PaletteMaterial001, 92]} instanceMatrix={nodes.mesh_45.instanceMatrix} />
      <instancedMesh args={[nodes.mesh_46.geometry, materials.PaletteMaterial001, 35]} instanceMatrix={nodes.mesh_46.instanceMatrix} />
      <instancedMesh args={[nodes.mesh_47.geometry, materials.PaletteMaterial001, 8]} instanceMatrix={nodes.mesh_47.instanceMatrix} />
      <instancedMesh args={[nodes.mesh_48.geometry, materials.PaletteMaterial001, 21]} instanceMatrix={nodes.mesh_48.instanceMatrix} />
      <instancedMesh args={[nodes.mesh_49.geometry, materials.PaletteMaterial001, 8]} instanceMatrix={nodes.mesh_49.instanceMatrix} />
      <instancedMesh args={[nodes.mesh_50.geometry, materials.PaletteMaterial001, 8]} instanceMatrix={nodes.mesh_50.instanceMatrix} />
      <instancedMesh args={[nodes.mesh_51.geometry, materials.PaletteMaterial001, 6]} instanceMatrix={nodes.mesh_51.instanceMatrix} />
    </group>
  )
}

useGLTF.preload('./coffee_shop-transformed.glb')
